GET http://localhost:4555/
Content-Type: application/json


###
POST http://localhost:4555/api/user
Content-Type: application/json

{
  "id": 3,
  "username": "user2",
  "role": "admin",
  "quests": []
}

###
GET http://localhost:4555/api/user
Content-Type: application/json

###
GET http://localhost:4555/api/user/2
Content-Type: application/json




###
POST http://localhost:4555/api/quests
Content-Type: application/json

{
  "title": "Delivery from the past",
  "map": "Customs",
  "trader": "Prapor",
  "link": "http://www.example.com"
}

###
GET http://localhost:4555/api/quests
Content-Type: application/json

###
GET http://localhost:4555/api/quests/1
Content-Type: application/json